### ISSUE TITLE
Reflections quiz

### ISSUE THREAD

**Issue by topshed** [raspberrypilearning/stress-ball#29]
When I went through the reflections quiz at the end, I was asked the same question 3 times. Then the final "Quiz complete" screen had a load of lorem ipsum text in it. 
![Snip20210623_5](https://user-images.githubusercontent.com/5092007/123053908-45ba7900-d3fc-11eb-9469-1b505d6c9de1.png)

**Comment by libxx1** [comment]
Removed reflection step as it wasn't supposed to be there for Stress Ball at the moment.
